### ISSUE TITLE
Allow turning off thumbnail cache

### ISSUE THREAD

**Issue by sysrqmagician** [sysrqmagician/extraneous#3]
Currently, the deArrow module caches thumbnails and titles in session storage. The user should have the option to disable thumbnail caching to save on memory.

**Comment by sysrqmagician** [comment]
The storage quota is much lower than I expected. Removed thumbnail caching.

**Comment by ajayyy** [comment]
It should be cached by the browser in the normal request cache anyway

**Comment by sysrqmagician** [comment]
Oh, yeah. I've had caching turned off locally for so long that I sometimes forget it exists.
